const rule = (
  id,
  tags,
  githubBehavior,
  explanation,
  suggestedAlternative,
  category = "Compatibility",
) => ({
  id,
  tags,
  githubBehavior,
  explanation,
  suggestedAlternative,
  category,
});
export const compatibilityRegistry = [
  rule(
    "common-html",
    [
      "picture",
      "source",
      "img",
      "p",
      "br",
      "kbd",
      "sup",
      "sub",
      "details",
      "summary",
      "table",
      "thead",
      "tbody",
      "tr",
      "th",
      "td",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "a",
      "strong",
      "em",
      "ul",
      "ol",
      "li",
      "blockquote",
      "pre",
      "code",
      "hr",
      "del",
    ],
    "Likely supported",
    "These common README elements generally render, but attributes and nesting may be restricted. README Studio preview may differ.",
    "Prefer simple Markdown or minimal semantic HTML; check the final README on GitHub.",
  ),
  rule(
    "container",
    ["div", "span", "center"],
    "Needs review",
    "Container styling is limited; GitHub may remove presentation attributes or legacy tags.",
    'Use Markdown, or a simple p align="center" around appropriate inline content.',
  ),
  rule(
    "executable",
    ["script", "object", "embed"],
    "Unsafe",
    "Executable content is unsafe and is removed from the Studio preview. GitHub commonly strips these elements.",
    "Use an image and a link to an external demonstration.",
    "Security",
  ),
  rule(
    "styling",
    ["style", "link"],
    "Likely stripped",
    "GitHub commonly strips style blocks, external CSS and custom styling. A README cannot depend on page CSS.",
    "Use Markdown structure or download and commit a self-contained image.",
  ),
  rule(
    "interactive",
    ["iframe", "form", "input", "button", "select", "textarea"],
    "Likely stripped",
    "Embedded forms and interactive documents are not dependable README features.",
    "Link to the interactive page instead.",
  ),
  rule(
    "media",
    ["video", "audio", "svg", "canvas"],
    "Needs review",
    "Raw media/graphics elements may be stripped or rendered differently. GitHub attachment handling is separate from arbitrary HTML support.",
    "Use an image or a normal link to media; store SVG as an image asset.",
  ),
];
export const compatibilityViews = [
  "All",
  "Likely supported",
  "Needs review",
  "Likely stripped",
  "Unsafe",
];
